class Board {
    constructor() {
        this.cells = [
            { "id": "0", "status": "off" }, 
            { "id": "1", "status": "off" },
            { "id": "2", "status": "off" },
            { "id": "3", "status": "off" },
            { "id": "4", "status": "off" },
            { "id": "5", "status": "off" },
            { "id": "6", "status": "off" },
            { "id": "7", "status": "off" },
            { "id": "8", "status": "off" },
            { "id": "9", "status": "off" },

            { "id": "10", "status": "off" },
            { "id": "11", "status": "off" },
            { "id": "12", "status": "off" },
            { "id": "13", "status": "off" },
            { "id": "14", "status": "off" },
            { "id": "15", "status": "off" },
            { "id": "16", "status": "off" },
            { "id": "17", "status": "off" },
            { "id": "18", "status": "off" },
            { "id": "19", "status": "off" },

            { "id": "20", "status": "off" },
            { "id": "21", "status": "off" },
            { "id": "22", "status": "off" },
            { "id": "23", "status": "off" },
            { "id": "24", "status": "off" },
            { "id": "25", "status": "off" },
            { "id": "26", "status": "off" },
            { "id": "27", "status": "off" },
            { "id": "28", "status": "off" },
            { "id": "29", "status": "off" },

            { "id": "30", "status": "off" },
            { "id": "31", "status": "off" },
            { "id": "32", "status": "off" },
            { "id": "33", "status": "off" },
            { "id": "34", "status": "off" },
            { "id": "35", "status": "off" },
            { "id": "36", "status": "off" },
            { "id": "37", "status": "off" },
            { "id": "38", "status": "off" },
            { "id": "39", "status": "off" },

            { "id": "40", "status": "off" },
            { "id": "41", "status": "off" },
            { "id": "42", "status": "off" },
            { "id": "43", "status": "off" },
            { "id": "44", "status": "off" },
            { "id": "45", "status": "off" },
            { "id": "46", "status": "off" },
            { "id": "47", "status": "off" },
            { "id": "48", "status": "off" },
            { "id": "49", "status": "off" },

            { "id": "50", "status": "off" },
            { "id": "51", "status": "off" },
            { "id": "52", "status": "off" },
            { "id": "53", "status": "off" },
            { "id": "54", "status": "off" },
            { "id": "55", "status": "off" },
            { "id": "56", "status": "off" },
            { "id": "57", "status": "off" },
            { "id": "58", "status": "off" },
            { "id": "59", "status": "off" },

            { "id": "60", "status": "off" },
            { "id": "61", "status": "off" },
            { "id": "62", "status": "off" },
            { "id": "63", "status": "off" },
            { "id": "64", "status": "off" },
            { "id": "65", "status": "off" },
            { "id": "66", "status": "off" },
            { "id": "67", "status": "off" },
            { "id": "68", "status": "off" },
            { "id": "69", "status": "off" },

            { "id": "70", "status": "off" },
            { "id": "71", "status": "off" },
            { "id": "72", "status": "off" },
            { "id": "73", "status": "off" },
            { "id": "74", "status": "off" },
            { "id": "75", "status": "off" },
            { "id": "76", "status": "off" },
            { "id": "77", "status": "off" },
            { "id": "78", "status": "off" },
            { "id": "79", "status": "off" },

            { "id": "80", "status": "off" },
            { "id": "81", "status": "off" },
            { "id": "82", "status": "off" },
            { "id": "83", "status": "off" },
            { "id": "84", "status": "off" },
            { "id": "85", "status": "off" },
            { "id": "86", "status": "off" },
            { "id": "87", "status": "off" },
            { "id": "88", "status": "off" },
            { "id": "89", "status": "off" },

            { "id": "90", "status": "off" },
            { "id": "91", "status": "off" },
            { "id": "92", "status": "off" },
            { "id": "93", "status": "off" },
            { "id": "94", "status": "off" },
            { "id": "95", "status": "off" },
            { "id": "96", "status": "off" },
            { "id": "97", "status": "off" },
            { "id": "98", "status": "off" },
            { "id": "99", "status": "off" }
        ]
    }

    returnCells() {
        return this.cells;
    }


}